### ISSUE TITLE
Uncaught TypeError: editor.unfoldSelectedLines is not a function

### ISSUE THREAD

**Issue by kalvia80** [MomsFriendlyDevCo/triple-folds#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Ubuntu 15.04
**Thrown From**: [triple-folds](https://github.com/MomsFriendlyDevCo/atom-triple-folds) package 0.1.1

### Stack Trace

Uncaught TypeError: editor.unfoldSelectedLines is not a function

```
At /home/francesco/.atom/packages/triple-folds/lib/index.js:126

TypeError: editor.unfoldSelectedLines is not a function
    at Object.toggleCollapse (/packages/triple-folds/lib/index.js:126:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -6:03.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-kui-simply-dark-syntax.theme-one-dark-ui)
  7x -5:54.7.0 core:move-down (input.hidden-input)
     -5:51.8.0 triple-folds:uncollapse-this (input.hidden-input)
     -4:27.4.0 triple-folds:unfold-all (input.hidden-input)
     -4:24.5.0 triple-folds:fold-all (input.hidden-input)
     -4:10 core:move-up (input.hidden-input)
  2x -4:09.0 core:backspace (input.hidden-input)
     -3:59.9.0 core:move-up (input.hidden-input)
     -3:49.4.0 clipboard-history:copy (input.hidden-input)
  7x -0:04.7.0 core:move-down (input.hidden-input)
     -0:02.3.0 triple-folds:uncollapse-this (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.12.1 
atom-html-preview 0.1.22 
atom-jshint 2.0.0 
atom-no-tab-close-button 1.0.0 
atom-pair 2.0.10 
autohide-tree-view 0.25.1 
class-complete 6.2.2 
clipboard-history 0.6.6 
color-picker 2.2.4 
dev-lorem 0.1.2 
expose 0.12.2 
file-icons 2.0.15 
find-selection 0.16.0 
firepad 0.8.0 
git-plus 5.16.2 
goto-definition 1.1.19 
goto-last-edit 0.3.2 
hacking-the-kernel 1.6.1 
hacking-the-kernel-ui 1.6.0 
increment-selection 0.3.0 
kui-simply-dark-syntax 0.0.0 
linter 1.11.21 
linter-jshint 3.0.2 
markdown-scroll-sync 2.1.2 
minimap 4.24.7 
minimap-bookmarks 0.3.1 
motepair 0.21.0 
multi-cursor-plus 1.2.0 
my-theme-syntax 0.0.0 
nav-panel 0.0.11 
nucleus 0.3.0 
open-in-browser 0.4.7 
open-terminal-here 2.2.0 
platformio-ide-terminal 2.2.2 
railscast-theme 0.3.0 
refraction-dark-syntax 1.1.0 
select-rectangle 1.0.2 
split-diff 1.0.3 
Sublime-Style-Column-Selection 1.7.2 
symbols-tree-view 0.13.2 
tab-close 2.0.3 
tag 0.4.0 
terminal-plus 0.14.5 
text-select-mode 0.4.0 
tidy-markdown 3.0.1 
todo-show 1.9.0 
tree-view-git-branch 0.1.2 
triple-folds 0.1.1 
vim-mode 0.65.1 
xml-formatter 0.10.0 
```

**Comment by hash-bang** [comment]
Fixed in 0.1.2.

Thanks for the error report.
